global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape MLflow metrics from Pushgateway
  - job_name: 'mlflow-metrics'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true

  # Scrape Pushgateway metrics
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s

  # Monitor the exporter itself if it exposes metrics
  - job_name: 'mlflow-exporter'
    static_configs:
      - targets: ['mlflow-exporter:8000']
    scrape_interval: 10s
    metrics_path: /metrics

  # Monitor Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093